1. 파이썬의 행렬 객체

- 파이썬에는 수학의 행렬을 나타내는 객체는 존재하지 않는다.
- 데이터과학분야(딥러닝)에서 행렬 연산이 많이 사용 된다.
- NumPy(Numerical Python)는 파이썬에서 수치 계산(Numerical Computing) 을 빠르고 편리하게 수행하기 위한 대표적인 라이브러리이다.
- 외부 라이브러리로 pip install numpy 명령으로 별로로 설치해야 한다.(아나콘다에는 포함되어 있다)

* 데이터 분석가/개발자/엔지니어가 행렬연산 직접 호출하는 일은 없다. 머신러닝, 딥러닝을 구현하면 내부적으로 행렬연산이 필요할때 NumPy 라이브러리를 이용해서 알아서 실행

In [ ]:
pip install numpy # 가상환경 내에 numpy 설치

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 12.4/12.4 MB 66.8 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
# 2. NumPy의 행렬 연산

import numpy as np

a = np.array([[1, 2],
             [3, 4]])
print(a)

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# [1+5  2+6] 
# [3+7  4+8]


c = np.array([[5, 6],
              [7, 8]])
d = np.array([[1, 2],
              [3, 4]])
print(c - d)


e = np.array([[1, 2],
              [3, 4]])
print(e * 10)

[[1 2]
 [3 4]]
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[10 20]
 [30 40]]


# 행렬 곱(Matrix Multiplication) 

- 앞 행렬의 열의 수와 뒤 행렬의 행의 수가 같아야
- 결과 행은 앞 행렬의 (행의 수 x 뒤 행렬의 열의 수)를 가지는 행렬이 된다.
- 2행3열 @ 3행1열 --> "2행1열"의 결과 행렬이 반환 된다. 
- 여기서 중요한 건 행렬곱연산은 행렬의 사이즈를 줄일 수 있다는 것이다. 
- 데이터 과학에선 입력값의 특성(피처, 변수)이 너무 많을때 압축할때 행렬곱연산을 사용한다.  

In [ ]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

# 전치행렬
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

In [ ]:
# 3. 머신러닝에서 행렬곱 연산

# 머신러닝 알고리즘에서 행렬 W와 벡터 x를 곱하면 결과의 차원(원소 개수)이 줄어들 수도 있다.
# 예를 들어, 3차원 벡터를 2차원 벡터로 변환하는 경우이다.

import numpy as np

# 2행 3열 행렬
W = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3차원 벡터
x = np.array([10, 20, 30]) # 3열
print("행렬곱 전 차원 : ", x.shape)

# 행렬 곱
y = W @ x

print(y) # 2열로 변경 됨 -> 차원축소
print("행렬곱 후 차원 : ", y.shape)