1. 파이썬의 행렬 객체

- 파이썬에는 수학의 행렬을 나타내는 객체는 존재하지 않는다.
- 데이터과학분야(딥러닝)에서 행렬 연산이 많이 사용 된다.
- NumPy(Numerical Python)는 파이썬에서 수치 계산(Numerical Computing) 을 빠르고 편리하게 수행하기 위한 대표적인 라이브러리이다.
- 외부 라이브러리로 pip install numpy 명령으로 별로로 설치해야 한다.(아나콘다에는 포함되어 있다)
- 데이터 분석가/개발자/엔지니어가 행렬연산 직접 호출하는 일은 없다. 머신러닝, 딥러닝을 구현하면 내부적으로 행렬연산이 필요할때 NumPy 라이브러리를 이용해서 알아서 실행

In [ ]:
pip install numpy # 가상환경 내에 numpy 설치

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 12.4/12.4 MB 66.8 MB/s  0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
# 2. NumPy의 행렬 연산

import numpy as np

a = np.array([[1, 2],
             [3, 4]]) # 리스트를 이용해 행렬 표현
print(a)
print(type(a)) # <class 'numpy.ndarray'> : n차원 배열의 행렬

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
# [1+5  2+6] 
# [3+7  4+8]


c = np.array([[5, 6],
              [7, 8]])
d = np.array([[1, 2],
              [3, 4]])
print(c - d)


e = np.array([[1, 2],
              [3, 4]])
print(e * 10)

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>
[[ 6  8]
 [10 12]]
[[4 4]
 [4 4]]
[[10 20]
 [30 40]]


In [ ]:
# 리스트 + 리스트
l = [[1, 2],[3, 4]] + [[5, 6],[7, 8]]
print(l)

# 행렬 + 행렬
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])
print(a + b) 
print(a * b) 
print(a @ b) # 행렬 곱 연산은 @로 표현

[[1, 2], [3, 4], [5, 6], [7, 8]]
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


< 행렬 곱(Matrix Multiplication) >

- 앞 행렬의 열의 수와 뒤 행렬의 행의 수가 같아야 계산 가능
- 결과 행은 앞 행렬의 (행의 수 x 뒤 행렬의 열의 수)를 가지는 행렬이 된다.
- 2행3열 @ 3행1열 --> "2행1열"의 결과 행렬이 반환 된다. 
- 여기서 중요한 건 행렬곱연산은 행렬의 사이즈를 줄일 수 있다는 것이다. 
- 데이터 과학에선 입력값의 특성(피처, 변수)이 너무 많을때 압축할때 행렬곱연산을 사용한다.  

In [15]:
import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])   # 2행3열

b = np.array([[10],
              [20],
              [30]])        # 3행1열

print(a @ b) # 결과는 2행1열 => 차원 축소! (기존 변수를 압축)
# [1×10 + 2×20 + 3×30]
# [4×10 + 5×20 + 6×30]

[[140]
 [320]]


In [ ]:
# 전치행렬(T) : 행과 열을 전치
a = np.array([[1, 2, 3],
              [4, 5, 6]])

print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
# 3. 머신러닝에서 행렬곱 연산

# 머신러닝 알고리즘에서 행렬 W와 벡터 x를 곱하면 결과의 차원(원소 개수)이 줄어들 수도 있다.
# 예를 들어, 3차원 벡터를 2차원 벡터로 변환하는 경우이다.

import numpy as np

# 2행 3열 행렬
W = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

# 3차원 벡터
x = np.array([10, 20, 30]) # 3열
print("행렬곱 전 차원 : ", x.shape)

# 행렬 곱
y = W @ x

print(y) # 2열로 변경 됨 -> 차원축소
print("행렬곱 후 차원 : ", y.shape)

행렬곱 전 차원 :  (3,)
[140 320]
행렬곱 후 차원 :  (2,)


** 머신러닝 비지도학습의 차원 축소(Dimensionality Reduction)에서 행렬곱이 사용되는 예 **

1. 특성(피처, x, 매개변수)이 많으면 다음 문제가 발생

- 계산량 증가
학습 시간, 메모리 사용량 증가

- 노이즈 증가
예측에 도움 안 되는 정보가 많아짐

- 과적합(Overfitting)
학습 데이터는 잘 맞추지만 새로운 데이터는 잘 못 맞춤

- 시각화 어려움
사람은 2차원, 3차원까지만 직관적으로 볼 수 있음

2. 차원 축소는 원래 데이터의 중요한 구조를 최대한 유지하면서 차원을 줄이는 것 이다.

제공된 특성(피처)를 압축하여, 적은 개수의 새로운 피처를 만들어낸다.
(피처의 수는 줄었지만 원본 데이터의 구조와 성질을 가장 가깝게 유지하는, 원래 데이터들의 관계가 크게 변하지 않게 만든다.)

- 피처가 다음과 같이 4일때
x1 = 연봉
x2 = 예금
x3 = 주식
x4 = 부동산

- 수식으로 나타내면 4개의 피처를 비율이 다르게 혼합한 피처 2개를 만든다.
z1 = (x1 * 0.5) + (x2 * 0.3) + (x3 * 0.1) + (x4 * 0.1)
z2 = (x1 * 0.2) + (x2 * 0.2) + (x3 * 0.3) + (x4 * 0.2)

(x1, x2, x3, x4)
↓
(z1, z2) # 원본성질을 가장 잘 지키는 피처를 구분해 내는 것이 목표!


>> 차원축소는 (x1, x2, x3, x4)의 구조/성질을 가장 가깝게 유지하는 (z1, z2)를 구하는 W(2행4열)값을 찾아 낸다. 
머신러닝/딥러닝은 입력(X)을 출력(Y)로 잘 변환할 수 있는 최적의 가중치 W(행렬)를 찾는 과정이다.

알고리즘에 따라
1. 수학적으로 직접 계산할 수도 있고 (PCA, 최소제곱법 선형회귀 등)
2. W를 반복적으로 수정하며 찾을 수도 있다.(로지스틱회귀, 신경망, 딥러닝 등)

선형대수에서 배우는 행렬 곱이 머신러닝과 딥러닝의 가장 중요한 수학 도구 중 하나다.
NumPy, TensorFlow, PyTorch도 내부적으로는 대부분 행렬 곱 연산을 수행한다.